/*
 * Use this script if you need to support IE 7 and IE 6. 
 * Inline HTML Comments have been removed as of IE10, so adding the script based on the comments requires additional markup just for IE10
 * Instead you can use this snippet to add the icons with the risk that if the user has disabled the access to the UA it will not work
*/
var Elusive  = Elusive || {};

;(function(window, document, undefined) {

  Elusive.Icons = {

		init : function(iev) {

			if (iev === -1 || iev >= 8) { return false; };

			var els = document.getElementsByTagName('*'),
				i, attr, c, el;

			for(i = els.length - 1; i >= 0; i--) {
				el = els[i];

				attr = el.getAttribute('data-icon');

				if(attr) { Elusive.Icons.addIcon(el, attr); };

				c = el.className;

				c = c.match(/icon-[^\s'"]+/);

				if(c && Elusive.Icons.icons[c[0]]) { Elusive.Icons.addIcon(el, Elusive.Icons.icons[c[0]]); };
			};
		},

		getIEV : function() {
	
			var rv = -1;

			if(navigator.appName == 'Microsoft Internet Explorer') {
			    var ua = navigator.userAgent;
			    var re  = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");

			    if(re.exec(ua) != null) {
			    	rv = parseFloat( RegExp.$1 );
			    };
			};

			return rv;
		},

		addIcon : function(el, entity) {
            var html = el.innerHTML;

            el.innerHTML = '<span style="font-family: \'Elusive-Icons\'">' + entity + '</span>' + html;
      	},

      	icons : {
			'icon-zoom-out': '&#xe000;',
			'icon-zoom-in': '&#xe001;',
			'icon-youtube': '&#xe002;',
			'icon-wrench-alt': '&#xe003;',
			'icon-wrench': '&#xe004;',
			'icon-wordpress': '&#xe005;',
			'icon-wheelchair': '&#xe006;',
			'icon-website-alt': '&#xe007;',
			'icon-website': '&#xe008;',
			'icon-warning-sign': '&#xe009;',
			'icon-w3c': '&#xe00a;',
			'icon-volume-up': '&#xe00b;',
			'icon-volume-off': '&#xe00c;',
			'icon-volume-down': '&#xe00d;',
			'icon-vimeo': '&#xe00e;',
			'icon-view-mode': '&#xe00f;',
			'icon-video-chat': '&#xe010;',
			'icon-video-alt': '&#xe011;',
			'icon-video': '&#xe012;',
			'icon-user': '&#xe013;',
			'icon-upload': '&#xe014;',
			'icon-unlock-alt': '&#xe015;',
			'icon-unlock': '&#xe016;',
			'icon-universal-access': '&#xe017;',
			'icon-twitter': '&#xe018;',
			'icon-tumblr': '&#xe019;',
			'icon-trash-alt': '&#xe01a;',
			'icon-trash': '&#xe01b;',
			'icon-torso': '&#xe01c;',
			'icon-tint': '&#xe01d;',
			'icon-time-alt': '&#xe01e;',
			'icon-time': '&#xe01f;',
			'icon-thumbs-up': '&#xe020;',
			'icon-thumbs-down': '&#xe021;',
			'icon-th-list': '&#xe022;',
			'icon-th-large': '&#xe023;',
			'icon-th': '&#xe024;',
			'icon-text-width': '&#xe025;',
			'icon-text-height': '&#xe026;',
			'icon-tasks': '&#xe027;',
			'icon-tags': '&#xe028;',
			'icon-tag': '&#xe029;',
			'icon-stumbleupon': '&#xe02a;',
			'icon-stop-alt': '&#xe02b;',
			'icon-stop': '&#xe02c;',
			'icon-step-forward': '&#xe02d;',
			'icon-step-backward': '&#xe02e;',
			'icon-star-empty': '&#xe02f;',
			'icon-star-alt': '&#xe030;',
			'icon-star': '&#xe031;',
			'icon-stackoverflow': '&#xe032;',
			'icon-speaker': '&#xe033;',
			'icon-smiley-alt': '&#xe034;',
			'icon-smiley': '&#xe035;',
			'icon-slideshare': '&#xe036;',
			'icon-skype': '&#xe037;',
			'icon-signal': '&#xe038;',
			'icon-shopping-cart-sign': '&#xe039;',
			'icon-shopping-cart': '&#xe03a;',
			'icon-share-alt': '&#xe03b;',
			'icon-share': '&#xe03c;',
			'icon-search-alt': '&#xe03d;',
			'icon-search': '&#xe03e;',
			'icon-screenshot': '&#xe03f;',
			'icon-screen-alt': '&#xe040;',
			'icon-screen': '&#xe041;',
			'icon-rss': '&#xe042;',
			'icon-road': '&#xe043;',
			'icon-reverse-alt': '&#xe044;',
			'icon-retweet': '&#xe045;',
			'icon-resize-vertical': '&#xe046;',
			'icon-resize-small': '&#xe047;',
			'icon-resize-horizontal': '&#xe048;',
			'icon-resize-full': '&#xe049;',
			'icon-repeat-alt': '&#xe04a;',
			'icon-repeat': '&#xe04b;',
			'icon-remove-sign': '&#xe04c;',
			'icon-remove-circle': '&#xe04d;',
			'icon-remove': '&#xe04e;',
			'icon-refresh': '&#xe04f;',
			'icon-reddit': '&#xe050;',
			'icon-record': '&#xe051;',
			'icon-random': '&#xe052;',
			'icon-quotes-alt': '&#xe053;',
			'icon-quotes': '&#xe054;',
			'icon-question-sign': '&#xe055;',
			'icon-question': '&#xe056;',
			'icon-qrcode': '&#xe057;',
			'icon-print': '&#xe058;',
			'icon-plus-sign': '&#xe059;',
			'icon-plus': '&#xe05a;',
			'icon-play-circle': '&#xe05b;',
			'icon-play-alt': '&#xe05c;',
			'icon-play': '&#xe05d;',
			'icon-plane': '&#xe05e;',
			'icon-pinterest': '&#xe05f;',
			'icon-picture': '&#xe060;',
			'icon-picasa': '&#xe061;',
			'icon-photo-alt': '&#xe062;',
			'icon-photo': '&#xe063;',
			'icon-phone-alt': '&#xe064;',
			'icon-phone': '&#xe065;',
			'icon-person': '&#xe066;',
			'icon-pencil-alt': '&#xe067;',
			'icon-pencil': '&#xe068;',
			'icon-pause-alt': '&#xe069;',
			'icon-pause': '&#xe06a;',
			'icon-path': '&#xe06b;',
			'icon-paper-clip-alt': '&#xe06c;',
			'icon-paper-clip': '&#xe06d;',
			'icon-ok-sign': '&#xe06e;',
			'icon-ok-circle': '&#xe06f;',
			'icon-ok': '&#xe070;',
			'icon-off': '&#xe071;',
			'icon-network': '&#xe072;',
			'icon-music': '&#xe073;',
			'icon-move': '&#xe074;',
			'icon-minus-sign': '&#xe075;',
			'icon-minus': '&#xe076;',
			'icon-mic-alt': '&#xe077;',
			'icon-mic': '&#xe078;',
			'icon-map-marker-alt': '&#xe079;',
			'icon-map-marker': '&#xe07a;',
			'icon-male': '&#xe07b;',
			'icon-magnet': '&#xe07c;',
			'icon-lock-alt': '&#xe07d;',
			'icon-lock': '&#xe07e;',
			'icon-list-alt': '&#xe07f;',
			'icon-list': '&#xe080;',
			'icon-linkedin': '&#xe081;',
			'icon-leaf': '&#xe082;',
			'icon-laptop-alt': '&#xe083;',
			'icon-laptop': '&#xe084;',
			'icon-key': '&#xe085;',
			'icon-italic': '&#xe086;',
			'icon-iphone-home': '&#xe087;',
			'icon-instagram': '&#xe088;',
			'icon-info-sign': '&#xe089;',
			'icon-indent-right': '&#xe08a;',
			'icon-indent-left': '&#xe08b;',
			'icon-hand-right': '&#xe08c;',
			'icon-hand-left': '&#xe08d;',
			'icon-hand-down': '&#xe08e;',
			'icon-guidedog': '&#xe08f;',
			'icon-group-alt': '&#xe090;',
			'icon-group': '&#xe091;',
			'icon-forward-alt': '&#xe092;',
			'icon-forward': '&#xe093;',
			'icon-fontsize': '&#xe094;',
			'icon-font': '&#xe095;',
			'icon-folder-sign': '&#xe096;',
			'icon-folder-open': '&#xe097;',
			'icon-female': '&#xe098;',
			'icon-fast-forward': '&#xe099;',
			'icon-fast-backward': '&#xe09a;',
			'icon-facetime-video': '&#xe09b;',
			'icon-facebook': '&#xe09c;',
			'icon-eye-open': '&#xe09d;',
			'icon-dashboard': '&#xe09e;',
			'icon-css': '&#xe09f;',
			'icon-credit-card': '&#xe0a0;',
			'icon-compass-alt': '&#xe0a1;',
			'icon-compass': '&#xe0a2;',
			'icon-comment-alt': '&#xe0a3;',
			'icon-chevron-down': '&#xe0a4;',
			'icon-check-empty': '&#xe0a5;',
			'icon-check': '&#xe0a6;',
			'icon-certificate': '&#xe0a7;',
			'icon-cc': '&#xe0a8;',
			'icon-camera': '&#xe0a9;',
			'icon-ban-circle': '&#xe0aa;',
			'icon-backward': '&#xe0ab;',
			'icon-asterisk': '&#xe0ac;',
			'icon-asl': '&#xe0ad;',
			'icon-arrow-up': '&#xe0ae;',
			'icon-arrow-right': '&#xe0af;',
			'icon-heart-alt': '&#xe0b0;',
			'icon-heart': '&#xe0b1;',
			'icon-hearing-impaired': '&#xe0b2;',
			'icon-headphones': '&#xe0b3;',
			'icon-hdd': '&#xe0b4;',
			'icon-hand-up': '&#xe0b5;',
			'icon-github': '&#xe0b6;',
			'icon-gift': '&#xe0b7;',
			'icon-fullscreen': '&#xe0b8;',
			'icon-friendfeed-rect': '&#xe0b9;',
			'icon-friendfeed': '&#xe0ba;',
			'icon-foursquare': '&#xe0bb;',
			'icon-file-new-alt': '&#xe0bc;',
			'icon-file-new': '&#xe0bd;',
			'icon-file-edit-alt': '&#xe0be;',
			'icon-file-edit': '&#xe0bf;',
			'icon-file-alt': '&#xe0c0;',
			'icon-file': '&#xe0c1;',
			'icon-dribble': '&#xe0c2;',
			'icon-download-alt': '&#xe0c3;',
			'icon-download': '&#xe0c4;',
			'icon-digg': '&#xe0c5;',
			'icon-deviantart': '&#xe0c6;',
			'icon-delicious': '&#xe0c7;',
			'icon-circle-arrow-left': '&#xe0c8;',
			'icon-circle-arrow-down': '&#xe0c9;',
			'icon-child': '&#xe0ca;',
			'icon-chevron-up': '&#xe0cb;',
			'icon-chevron-right': '&#xe0cc;',
			'icon-chevron-left': '&#xe0cd;',
			'icon-bold': '&#xe0ce;',
			'icon-blogger': '&#xe0cf;',
			'icon-blind': '&#xe0d0;',
			'icon-bell': '&#xe0d1;',
			'icon-behance': '&#xe0d2;',
			'icon-barcode': '&#xe0d3;',
			'icon-arrow-left': '&#xe0d4;',
			'icon-arrow-down': '&#xe0d5;',
			'icon-align-right': '&#xe0d6;',
			'icon-align-left': '&#xe0d7;',
			'icon-align-justify': '&#xe0d8;',
			'icon-align-center': '&#xe0d9;',
			'icon-adult': '&#xe0da;',
			'icon-adjust': '&#xe0db;',
			'icon-address-book-alt': '&#xe0dc;',
			'icon-address-book': '&#xe0dd;',
			'icon-idea': '&#xe0de;',
			'icon-home-alt': '&#xe0df;',
			'icon-home': '&#xe0e0;',
			'icon-heart-empty': '&#xe0e1;',
			'icon-globe': '&#xe0e2;',
			'icon-glasses': '&#xe0e3;',
			'icon-glass': '&#xe0e4;',
			'icon-github-text': '&#xe0e5;',
			'icon-flag': '&#xe0e6;',
			'icon-fire': '&#xe0e7;',
			'icon-filter': '&#xe0e8;',
			'icon-film': '&#xe0e9;',
			'icon-envelope-alt': '&#xe0ea;',
			'icon-envelope': '&#xe0eb;',
			'icon-eject': '&#xe0ec;',
			'icon-edit': '&#xe0ed;',
			'icon-cloud-alt': '&#xe0ee;',
			'icon-cloud': '&#xe0ef;',
			'icon-circle-arrow-up': '&#xe0f0;',
			'icon-circle-arrow-right': '&#xe0f1;',
			'icon-braille': '&#xe0f2;',
			'icon-bookmark-empty': '&#xe0f3;',
			'icon-bookmark': '&#xe0f4;',
			'icon-book': '&#xe0f5;',
			'icon-inbox-box': '&#xe0f6;',
			'icon-inbox-alt': '&#xe0f7;',
			'icon-inbox': '&#xe0f8;',
			'icon-idea-alt': '&#xe0f9;',
			'icon-graph-alt': '&#xe0fa;',
			'icon-graph': '&#xe0fb;',
			'icon-googleplus': '&#xe0fc;',
			'icon-globe-alt': '&#xe0fd;',
			'icon-folder-close': '&#xe0fe;',
			'icon-folder': '&#xe0ff;',
			'icon-flickr': '&#xe100;',
			'icon-flag-alt': '&#xe101;',
			'icon-eye-close': '&#xe102;',
			'icon-exclamation-sign': '&#xe103;',
			'icon-error-alt': '&#xe104;',
			'icon-error': '&#xe105;',
			'icon-comment': '&#xe106;',
			'icon-cogs': '&#xe107;',
			'icon-cog-alt': '&#xe108;',
			'icon-cog': '&#xe109;',
			'icon-calendar-sign': '&#xe10a;',
			'icon-calendar': '&#xe10b;',
			'icon-bullhorn': '&#xe10c;',
			'icon-briefcase': '&#xe10d;',
			'icon-vkontakte': '&#xe10e;'
		}
	};
	/*
	 * Initiate the icons addition if the browser version is less than 8
	*/
	Elusive.Icons.init(Elusive.Icons.getIEV()); 

})(window, document);
